

CREATE TABLE Book (
    Id INTEGER PRIMARY KEY IDENTITY,
    Title VARCHAR(500) NOT NULL,
    ISBN VARCHAR(500) NOT NULL
);

CREATE TABLE Author (
    Id INTEGER PRIMARY KEY IDENTITY,
    AuthorName VARCHAR(500) NOT NULL,
);

CREATE TABLE AuthorBook (
    Id INTEGER PRIMARY KEY IDENTITY,
    BookId INTEGER NOT NULL,
    AuthorId INTEGER NOT NULL,
    FOREIGN KEY (BookId) REFERENCES Book(Id),
    FOREIGN KEY (AuthorId) REFERENCES Author(Id)
);

CREATE TABLE LibraryUser (
    Id INTEGER PRIMARY KEY IDENTITY,
    UserName VARCHAR(500) NOT NULL,
    PassWord  VARCHAR(500) NOT NULL
);

CREATE TABLE Loan (
    Id INTEGER PRIMARY KEY IDENTITY,
    BookId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY (BookId) REFERENCES Book(Id),
    FOREIGN KEY (UserId) REFERENCES LibraryUser(Id)
)